### ISSUE TITLE
Create design for armonaut.yml build configuration

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/armonaut-start#31]
```yaml
env:
  - secure:
      - [ENCRYPTED ENV VAR]
  - NAME=VALUE

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly

jobs:
  - env: NAME2=VALUE2
    os: ubuntu
    version: 16.04
    sudo: true

  - os: raspbian
    version: stretch
    sudo: false

cache:
  - pip
  - directories:
    - ~/.cache

install:
  - python -m pip install tox

script:
  - tox
```
